contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: "This sub-playbook works with the parent, and will loop over the passed
  in data, and IF there is a Base64 key, it will decode it, and return a new key called
  LoopData with contained the original Base64 and the decoded base 64. \n\nMake sure
  to check the Playbook Inputs/Outputs to see what to pass in, and what this playbook
  will output to the parent. "
id: 66ddbd3c-f624-49fa-8544-70ef48d25e3c
inputs:
- description: 'The array of data to pass in. '
  key: data
  playbookInputQuery: null
  required: false
  value: {}
name: XSOAR Engineer Training - Training 1 - Scenario 1 - Sub-Playbook
outputs:
- contextPath: LoopData
  description: The parsed data with decoded base64.
  type: unknown
sourceplaybookid: XSOAR Engineer Training - For Each Loops (Sub-Playbook)
starttaskid: "0"
tags:
- training
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2979cc22-1622-43eb-8760-eb6a6e990eb3
      iscommand: false
      name: ""
      version: -1
    taskid: 2979cc22-1622-43eb-8760-eb6a6e990eb3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: LoopData
      stringify:
        simple: "false"
      value:
        complex:
          root: inputs.data
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered.

        We set a  new key with our input data
      id: 0777e6be-21b5-431d-8243-d60f5e827479
      iscommand: false
      name: Set Loop Data Key
      script: Set
      type: regular
      version: -1
    taskid: 0777e6be-21b5-431d-8243-d60f5e827479
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context

        Here we delete the context from the sub-playbook only, as we want to keep outputting a new LoopData key.
      id: d1678149-b847-4ebe-80e5-fa0219c52db9
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: d1678149-b847-4ebe-80e5-fa0219c52db9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Base64
                root: inputs.data
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Base64
                root: inputs.data
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Here we check if the data we are looping over has the key of Base64
        that we want to decode. '
      id: 7793f28e-40e5-47ee-8905-d3babb20ec1a
      iscommand: false
      name: Is there a Base64 Key to decode?
      type: condition
      version: -1
    taskid: 7793f28e-40e5-47ee-8905-d3babb20ec1a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Base64
          root: LoopData
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Decodes an input in Base64 format.\n\nDecode the Base64 key from
        that. "
      id: 5d8aea8e-f8eb-48e7-83a7-2c58004b7068
      iscommand: false
      name: Decode Base 64 Key
      script: Base64Decode
      type: regular
      version: -1
    taskid: 5d8aea8e-f8eb-48e7-83a7-2c58004b7068
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      keys:
        simple: DecodedBase64
      parent:
        simple: LoopData
      values:
        complex:
          accessor: decoded
          root: Base64
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Set multiple keys/values to the context.\n\nAnd then add the decoded
        value back into LoopData, so now we have the original and decoded values. "
      id: 0a00f3d8-d496-40cf-81f5-c48a68239fe1
      iscommand: false
      name: Update LoopData with decoded value
      script: SetMultipleValues
      type: regular
      version: -1
    taskid: 0a00f3d8-d496-40cf-81f5-c48a68239fe1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e1f7f07f-012c-4f8f-801b-8fbd92cd2dff
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e1f7f07f-012c-4f8f-801b-8fbd92cd2dff
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
